apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-question-deployment
  labels:
    app: last-question
spec:
  replicas: 2
  selector:
    matchLabels:
      app: last-question
  template:
    metadata:
      labels:
        app: last-question
    spec:
      containers:
        - name: last-question
          image: '15758622001/devops-mp:lts'
          ports:
            - containerPort: 8080

#'tpgldevopsacr.azurecr.io/devops/tp4:latest'