apiVersion: v1
kind: Service
metadata:
  name: last-question-service
spec:
  selector:
    app: last-question  # Le sélecteur correspond à celui défini dans le fichier de déploiement
  type : LoadBalancer
  ports:
    - name: http
      port: 30000 # Le port sur lequel le service écoute
      protocol: TCP
      targetPort: 8080  # Le port sur lequel les pods du déploiement écoutent
